# Production Docker Compose Configuration
# Usage: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

version: "3.8"

services:
  resolver:
    image: bmn-resolver:latest
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
        reservations:
          cpus: "1"
          memory: 1G
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      - DENO_ENV=production
      - LOG_LEVEL=warn
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "20"
        compress: "true"

  alice:
    image: bmn-alice:latest
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      - DENO_ENV=production
      - LOG_LEVEL=warn
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "20"
        compress: "true"

  bob:
    image: bmn-bob:latest
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      - DENO_ENV=production
      - LOG_LEVEL=warn
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "20"
        compress: "true"

  # Monitoring stack removed in production overlay: redis, prometheus, grafana
