services:
  # Alice service (swap initiator)
  alice:
    build:
      context: .
      dockerfile: Dockerfile.alice
      args:
        - BUILDKIT_INLINE_CACHE=1
    container_name: bmn-alice
    hostname: alice
    environment:
      - DENO_ENV=production
      - DENO_KV_PATH=/app/data/kv/alice.db
      - DENO_DIR=/app/data/cache
      - SERVICE_NAME=alice
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - INDEXER_URL=http://host.docker.internal:42069
      - RESOLVER_URL=http://bob:8002
    env_file:
      - .env
    volumes:
      # Shared data directory
      - bmn-data:/app/data
    ports:
      - "8001:8001"  # Alice API
    restart: unless-stopped
    depends_on:
      - bob
    networks:
      - bmn-network
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    labels:
      - "com.bmn.service=alice"
      - "com.bmn.role=initiator"

  # Bob-Resolver service (unified swap acceptor/taker and resolver coordinator)
  bob:
    build:
      context: .
      dockerfile: Dockerfile.bob
      args:
        - BUILDKIT_INLINE_CACHE=1
    container_name: bmn-bob-resolver
    hostname: bob
    environment:
      - DENO_ENV=production
      - DENO_KV_PATH=/app/data/kv/bob.db
      - DENO_DIR=/app/data/cache
      - SERVICE_NAME=bob-resolver
      - SERVICE_MODE=bob-resolver
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - INDEXER_URL=http://host.docker.internal:42069
      # Environment variables for unified Bob-Resolver service
      - RESOLVER_PRIVATE_KEY=${RESOLVER_PRIVATE_KEY}
      - BOB_PRIVATE_KEY=${BOB_PRIVATE_KEY:-${RESOLVER_PRIVATE_KEY}}
      - ANKR_API_KEY=${ANKR_API_KEY}
      - POLLING_INTERVAL=${POLLING_INTERVAL:-10000}
      - MIN_PROFIT_BPS=${MIN_PROFIT_BPS:-0}
    env_file:
      - .env
    volumes:
      # Shared data directory
      - bmn-data:/app/data
    ports:
      - "8002:8002"  # Bob-Resolver API
    restart: unless-stopped
    # No dependencies - Bob-Resolver is the main service
    networks:
      - bmn-network
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    labels:
      - "com.bmn.service=bob-resolver"
      - "com.bmn.role=acceptor-resolver"

  # Monitoring stack removed: redis, prometheus, grafana

networks:
  bmn-network:
    external: true
    name: ${DOCKER_SHARED_NETWORK:-bmn-network}

volumes:
  # Named volumes for better management
  bmn-data:
    driver: local