services:
  # Main resolver service (acts as coordinator and Bob/taker)
  resolver:
    build:
      context: .
      dockerfile: Dockerfile.resolver
      # Always use cache by default
      args:
        - BUILDKIT_INLINE_CACHE=1
    container_name: bmn-resolver
    hostname: resolver
    environment:
      - DENO_ENV=production
      - DENO_KV_PATH=/app/data/kv/resolver.db
      - DENO_DIR=/app/data/cache
      - SERVICE_NAME=resolver
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - INDEXER_URL=http://host.docker.internal:42069
    env_file:
      - .env
    volumes:
      # Shared data directory for persistent storage
      - bmn-data:/app/data
    ports:
      - "8000:8000"  # Resolver API
    restart: unless-stopped
    networks:
      - bmn-network
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    labels:
      - "com.bmn.service=resolver"
      - "com.bmn.role=coordinator"

  # Alice service (swap initiator)
  alice:
    build:
      context: .
      dockerfile: Dockerfile.alice
      args:
        - BUILDKIT_INLINE_CACHE=1
    container_name: bmn-alice
    hostname: alice
    environment:
      - DENO_ENV=production
      - DENO_KV_PATH=/app/data/kv/alice.db
      - DENO_DIR=/app/data/cache
      - SERVICE_NAME=alice
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - INDEXER_URL=http://host.docker.internal:42069
      - RESOLVER_URL=http://resolver:8000
    env_file:
      - .env
    volumes:
      # Shared data directory
      - bmn-data:/app/data
    ports:
      - "8001:8001"  # Alice API
    restart: unless-stopped
    depends_on:
      - resolver
    networks:
      - bmn-network
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    labels:
      - "com.bmn.service=alice"
      - "com.bmn.role=initiator"

  # Bob service (swap acceptor/taker - separate instance of resolver)
  bob:
    build:
      context: .
      dockerfile: Dockerfile.bob
      args:
        - BUILDKIT_INLINE_CACHE=1
    container_name: bmn-bob
    hostname: bob
    environment:
      - DENO_ENV=production
      - DENO_KV_PATH=/app/data/kv/bob.db
      - DENO_DIR=/app/data/cache
      - SERVICE_NAME=bob
      - SERVICE_MODE=bob
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - INDEXER_URL=http://host.docker.internal:42069
      - RESOLVER_URL=http://resolver:8000
    env_file:
      - .env
    volumes:
      # Shared data directory
      - bmn-data:/app/data
    ports:
      - "8002:8002"  # Bob API
    restart: unless-stopped
    depends_on:
      - resolver
    networks:
      - bmn-network
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    labels:
      - "com.bmn.service=bob"
      - "com.bmn.role=acceptor"

  # Monitoring stack removed: redis, prometheus, grafana

networks:
  bmn-network:
    external: true
    name: ${DOCKER_SHARED_NETWORK:-bmn-network}

volumes:
  # Named volumes for better management
  bmn-data:
    driver: local